default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: graphql_development
  username: postgres

test:
  <<: *default
  database: graphql_test
  username: postgres
